kind : Deployment
apiVersion : apps/v1
metadata :
  name : backend-deployment
  namespace : garden
spec:
  replicas : 1
  selector :
    matchLabels :
      app : backend
  template :
    metadata :  
      name : backend-pod
      namespace : garden
      labels :
        app : backend
    spec :
      containers :
      - name : backend-container
        image : vmadiwalkar/backend:latest
        ports :
        - containerPort : 8080
        env:
            - name: DATABASE_URL
              value: "postgresql://ps_user:SecurePasswords@postgres:5432/postgres" 